# Generated by Django 5.1.3 on 2024-11-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='question', to='cases.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ManyToManyField(related_name='correct_question', to='cases.answer'),
        ),
    ]
